service: product-service
frameworkVersion: "3"

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  catalogItemsQueueName: catalogItemsQueue
  createProductTopicName: createProductTopic

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
        - "sqs:GetQueueUrl"
      Resource: "arn:aws:sqs:*:*:*"
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource:
        Ref: CreateProductTopic

functions:
  catalogBatchProcess:
    handler: handlers/catalogBatchProcess.catalogBatchProcess
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - CatalogItemsQueue
              - Arn
          batchSize: 5
  # importFileParser:
  #   handler: handlers/importFileParser.handler
  #   environment:
  #     SQS_URL:
  #       Ref: CatalogItemsQueue
  getProductsList:
    handler: handlers/getProductsList.getProductsList
    events:
      - http:
          method: get
          path: products
          cors: true
  getProductById:
    handler: handlers/getProductById.getProductById
    events:
      - http:
          method: get
          path: products/{id}
          cors: true
  createProduct:
    handler: handlers/createProducts.createProducts
    environment:
      tableName: products
    events:
      - http:
          method: post
          path: products
          cors: true

resources:
  Resources:
    CatalogItemsQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:custom.catalogItemsQueueName}
    CreateProductTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: ${self:custom.createProductTopicName}
    ProductTopicSubscription:
      Type: "AWS::SNS::Subscription"
      Properties:
        TopicArn:
          Ref: CreateProductTopic
        Protocol: email
        Endpoint: "olhamorozowa@gmail.com"

