service: import-service

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:DeleteObject"
        - "s3:PutObject"
        - "s3:GetObject"
      Resource: "arn:aws:s3:::bukethw5/*"

functions:
  importProductsFile:
    handler: handlers/importProductsFile.handler
    events:
      - http:
          path: import
          method: get
          cors: true

  importFileParser:
    handler: handlers/importFileParser.handler
    events:
      - s3:
          bucket: bukethw5
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
          cors: true

custom:
  importBucket: bukethw5
